-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 16:14:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ciudades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ciudades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ciudades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(105) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`direcciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ciudad_id_idx` (`ciudad_id` ASC) VISIBLE,
  CONSTRAINT `ciudad_id`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `mydb`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `name` VARCHAR(16) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(200) NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `apellido` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `id_direccion` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT NULL DEFAULT 0,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `remember_me` TINYINT NOT NULL DEFAULT 0,
  `foto` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `id_direccion_idx` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `id_direccion`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_padre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precio` FLOAT NOT NULL,
  `ciudad_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `categoria_id` INT NOT NULL,
  `valoracion` FLOAT NULL,
  `is_usado` TINYINT NULL DEFAULT 0,
  `meses_uso` INT NULL DEFAULT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `estado_uso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `id_usuario_productos`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_categoria_productos`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valoraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`valoraciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`valoraciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `valoracion` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_usuario_valoraciones`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto_valoraciones`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `comentario` VARCHAR(100) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_usuario_comentarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`empresas_envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`empresas_envio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`empresas_envio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_direccion` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metodos_envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metodos_envio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metodos_envio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `costo_envio` FLOAT NOT NULL,
  `tiempo_envio` INT NOT NULL,
  `radio_entrega` FLOAT NULL,
  `id_empresa` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `id_empresa_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`empresas_envio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fotos_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fotos_productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fotos_productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_producto` INT NOT NULL,
  `path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_producto_fotos`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos_listas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`productos_listas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`productos_listas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_producto_listas`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listas_deseados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`listas_deseados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`listas_deseados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `id_productos_lista` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `id_productos_lista_idx` (`id_productos_lista` ASC) VISIBLE,
  CONSTRAINT `id_productos_lista_lista_deseados`
    FOREIGN KEY (`id_productos_lista`)
    REFERENCES `mydb`.`productos_listas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metodos_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metodos_de_pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metodos_de_pago` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `tiene_recargo` TINYINT NULL DEFAULT 0,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado_envio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado_envio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `fecha_envio` DATE NOT NULL,
  `fecha_estimada` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metodo_pago_especifico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metodo_pago_especifico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metodo_pago_especifico` (
  `id` INT NOT NULL,
  `numero_transaccion` INT NOT NULL,
  `titular` VARCHAR(200) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_vencimiento` DATE NULL,
  `id_metodo_pago` INT NOT NULL,
  `numero_tarjeta` INT NULL,
  `tipo_tarjeta` VARCHAR(45) NULL,
  `entidad_bancaria` VARCHAR(65) NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cvu` INT NULL,
  `alias` VARCHAR(65) NULL,
  `cuenta_bancaria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_metodo_idx` (`id_metodo_pago` ASC) VISIBLE,
  CONSTRAINT `id_metodo01`
    FOREIGN KEY (`id_metodo_pago`)
    REFERENCES `mydb`.`metodos_de_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ventas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_comprador` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `fecha_venta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_direccion_envio` INT NOT NULL,
  `id_metodo_envio` INT NOT NULL,
  `id_metodo_pago` INT NOT NULL,
  `id_estado_envio` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `id_comprador_idx` (`id_comprador` ASC) VISIBLE,
  INDEX `id_direccion_idx` (`id_direccion_envio` ASC) VISIBLE,
  INDEX `id_metodo_envio_idx` (`id_metodo_envio` ASC) VISIBLE,
  INDEX `id_estado_envio_idx` (`id_estado_envio` ASC) VISIBLE,
  INDEX `id_metodo_pago_idx` (`id_metodo_pago` ASC) VISIBLE,
  CONSTRAINT `id_comprador`
    FOREIGN KEY (`id_comprador`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_direccion_ventas`
    FOREIGN KEY (`id_direccion_envio`)
    REFERENCES `mydb`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_metodo_envio_ventas`
    FOREIGN KEY (`id_metodo_envio`)
    REFERENCES `mydb`.`metodos_envio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_metodo_pago_ventas`
    FOREIGN KEY (`id_metodo_pago`)
    REFERENCES `mydb`.`metodo_pago_especifico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_estado_envio_ventas`
    FOREIGN KEY (`id_estado_envio`)
    REFERENCES `mydb`.`estado_envio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ventas_detalle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ventas_detalle` (
  `id` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `precio_unitario` FLOAT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  `id_venta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_venta_idx` (`id_venta` ASC) VISIBLE,
  CONSTRAINT `id_venta`
    FOREIGN KEY (`id_venta`)
    REFERENCES `mydb`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
